============================= test session starts ==============================
platform darwin -- Python 3.11.13, pytest-8.4.1, pluggy-1.6.0 -- /opt/homebrew/opt/python@3.11/bin/python3.11
cachedir: .pytest_cache
rootdir: /Users/user/Documents/GitHub/manticore
configfile: pyproject.toml
plugins: anyio-4.9.0, cov-6.2.1
collecting ... collected 161 items

tests/ethereum/test_detectors.py::EthRetVal::test_retval_crazy FAILED    [  0%]
tests/ethereum/test_detectors.py::EthRetVal::test_retval_lunatic FAILED  [  1%]
tests/ethereum/test_detectors.py::EthRetVal::test_retval_not_ok FAILED   [  1%]
tests/ethereum/test_detectors.py::EthRetVal::test_retval_ok FAILED       [  2%]
tests/ethereum/test_detectors.py::EthSuicidal::test_selfdestruct_true_neg FAILED [  3%]
tests/ethereum/test_detectors.py::EthSuicidal::test_selfdestruct_true_neg1 FAILED [  3%]
tests/ethereum/test_detectors.py::EthSuicidal::test_selfdestruct_true_pos FAILED [  4%]
tests/ethereum/test_detectors.py::EthSuicidal::test_selfdestruct_true_pos1 SKIPPED [  4%]
tests/ethereum/test_detectors.py::EthExternalCallAndLeak::test_etherleak_true_neg FAILED [  5%]
tests/ethereum/test_detectors.py::EthExternalCallAndLeak::test_etherleak_true_neg1 FAILED [  6%]
tests/ethereum/test_detectors.py::EthExternalCallAndLeak::test_etherleak_true_neg2 FAILED [  6%]
tests/ethereum/test_detectors.py::EthExternalCallAndLeak::test_etherleak_true_neg3 FAILED [  7%]
tests/ethereum/test_detectors.py::EthExternalCallAndLeak::test_etherleak_true_pos_argument SKIPPED [  8%]
tests/ethereum/test_detectors.py::EthExternalCallAndLeak::test_etherleak_true_pos_argument1 SKIPPED [  8%]
tests/ethereum/test_detectors.py::EthExternalCallAndLeak::test_etherleak_true_pos_argument2 SKIPPED [  9%]
tests/ethereum/test_detectors.py::EthExternalCallAndLeak::test_etherleak_true_pos_msgsender FAILED [  9%]
tests/ethereum/test_detectors.py::EthExternalCallAndLeak::test_etherleak_true_pos_msgsender1 SKIPPED [ 10%]
tests/ethereum/test_detectors.py::EthIntegerOverflow::test_mul_no_overflow PASSED [ 11%]
tests/ethereum/test_detectors.py::EthIntegerOverflow::test_mul_overflow0 PASSED [ 11%]
tests/ethereum/test_detectors.py::EthIntegerOverflow::test_mul_overflow1 PASSED [ 12%]
tests/ethereum/test_detectors.py::EthEnvInstruction::test_predictable_not_ok FAILED [ 13%]
tests/ethereum/test_detectors.py::EthDelegatecall::test_delegatecall_not_ok SKIPPED [ 13%]
tests/ethereum/test_detectors.py::EthDelegatecall::test_delegatecall_not_ok1 SKIPPED [ 14%]
tests/ethereum/test_detectors.py::EthDelegatecall::test_delegatecall_ok FAILED [ 14%]
tests/ethereum/test_detectors.py::EthDelegatecall::test_delegatecall_ok1 SKIPPED [ 15%]
tests/ethereum/test_detectors.py::EthDelegatecall::test_delegatecall_ok2 SKIPPED [ 16%]
tests/ethereum/test_detectors.py::EthDelegatecall::test_delegatecall_ok3 SKIPPED [ 16%]
tests/ethereum/test_detectors.py::EthRaceCondition::test_race_condition FAILED [ 17%]
tests/ethereum/test_detectors.py::EthRaceCondition::test_race_condition2 SKIPPED [ 18%]
tests/ethereum/test_detectors.py::EthBalance::test_balance_not_ok FAILED [ 18%]
tests/ethereum/test_detectors.py::EthBalance::test_balance_ok FAILED     [ 19%]
tests/ethereum/test_general.py::EthDetectorsIntegrationTest::test_int_ovf FAILED [ 19%]
tests/ethereum/test_general.py::EthVerifierIntegrationTest::test_propverif FAILED [ 20%]
tests/ethereum/test_general.py::EthVerifierIntegrationTest::test_propverif_external PASSED [ 21%]
tests/ethereum/test_general.py::EthAbiTests::test_address0 PASSED        [ 21%]
tests/ethereum/test_general.py::EthAbiTests::test_dyn_address PASSED     [ 22%]
tests/ethereum/test_general.py::EthAbiTests::test_dyn_bytes PASSED       [ 22%]
tests/ethereum/test_general.py::EthAbiTests::test_empty_types PASSED     [ 23%]
tests/ethereum/test_general.py::EthAbiTests::test_function_type FAILED   [ 24%]
tests/ethereum/test_general.py::EthAbiTests::test_mult_dyn_types PASSED  [ 24%]
tests/ethereum/test_general.py::EthAbiTests::test_parse_invalid_int PASSED [ 25%]
tests/ethereum/test_general.py::EthAbiTests::test_parse_invalid_int_negative PASSED [ 26%]
tests/ethereum/test_general.py::EthAbiTests::test_parse_invalid_int_not_pow_of_two PASSED [ 26%]
tests/ethereum/test_general.py::EthAbiTests::test_parse_invalid_int_too_big PASSED [ 27%]
tests/ethereum/test_general.py::EthAbiTests::test_parse_tx FAILED        [ 27%]
tests/ethereum/test_general.py::EthAbiTests::test_parse_valid_int0 PASSED [ 28%]
tests/ethereum/test_general.py::EthAbiTests::test_parse_valid_int1 PASSED [ 29%]
tests/ethereum/test_general.py::EthAbiTests::test_parse_valid_int2 PASSED [ 29%]
tests/ethereum/test_general.py::EthAbiTests::test_self_make_and_parse_multi_dyn FAILED [ 30%]
tests/ethereum/test_general.py::EthAbiTests::test_serialize_basic_types_int PASSED [ 31%]
tests/ethereum/test_general.py::EthAbiTests::test_serialize_basic_types_int16 PASSED [ 31%]
tests/ethereum/test_general.py::EthAbiTests::test_serialize_basic_types_int8 PASSED [ 32%]
tests/ethereum/test_general.py::EthAbiTests::test_serialize_basic_types_uint PASSED [ 32%]
tests/ethereum/test_general.py::EthAbiTests::test_serialize_bytesM_symbolic PASSED [ 33%]
tests/ethereum/test_general.py::EthAbiTests::test_serialize_bytes_symbolic PASSED [ 34%]
tests/ethereum/test_general.py::EthAbiTests::test_serialize_fixed_bytes2 PASSED [ 34%]
tests/ethereum/test_general.py::EthAbiTests::test_serialize_fixed_bytes32 PASSED [ 35%]
tests/ethereum/test_general.py::EthAbiTests::test_serialize_fixed_bytes_less_data PASSED [ 36%]
tests/ethereum/test_general.py::EthAbiTests::test_serialize_fixed_bytes_too_big PASSED [ 36%]
tests/ethereum/test_general.py::EthAbiTests::test_serialize_tuple PASSED [ 37%]
tests/ethereum/test_general.py::EthAbiTests::test_simple_types0 PASSED   [ 37%]
tests/ethereum/test_general.py::EthAbiTests::test_simple_types1 PASSED   [ 38%]
tests/ethereum/test_general.py::EthAbiTests::test_simple_types_ints PASSED [ 39%]
tests/ethereum/test_general.py::EthAbiTests::test_simple_types_ints_symbolic PASSED [ 39%]
tests/ethereum/test_general.py::EthAbiTests::test_simple_types_ints_symbolic1 PASSED [ 40%]
tests/ethereum/test_general.py::EthAbiTests::test_str_for_string_bytesM_arg PASSED [ 40%]
tests/ethereum/test_general.py::EthAbiTests::test_valid_uint PASSED      [ 41%]
tests/ethereum/test_general.py::EthInstructionTests::test_SDIV PASSED    [ 42%]
tests/ethereum/test_general.py::EthInstructionTests::test_SDIVS1 PASSED  [ 42%]
tests/ethereum/test_general.py::EthInstructionTests::test_SDIVS2 PASSED  [ 43%]
tests/ethereum/test_general.py::EthInstructionTests::test_SDIVS3 PASSED  [ 44%]
tests/ethereum/test_general.py::EthInstructionTests::test_SDIVSx PASSED  [ 44%]
tests/ethereum/test_general.py::EthInstructionTests::test_str PASSED     [ 45%]
tests/ethereum/test_general.py::EthTests::test_account_names FAILED      [ 45%]
tests/ethereum/test_general.py::EthTests::test_call_with_concretized_args FAILED [ 46%]
tests/ethereum/test_general.py::EthTests::test_check_jumpdest_symbolic_pc FAILED [ 47%]
tests/ethereum/test_general.py::EthTests::test_contract_create_and_access_non_existing_function FAILED [ 47%]
tests/ethereum/test_general.py::EthTests::test_contract_create_and_call_underscore_function FAILED [ 48%]
tests/ethereum/test_general.py::EthTests::test_create_bytecode_contract FAILED [ 49%]
tests/ethereum/test_general.py::EthTests::test_create_contract_two_instances FAILED [ 49%]
tests/ethereum/test_general.py::EthTests::test_create_contract_with_string_args FAILED [ 50%]
tests/ethereum/test_general.py::EthTests::test_create_contract_with_too_much_args FAILED [ 50%]
tests/ethereum/test_general.py::EthTests::test_emit_did_execute_end_instructions FAILED [ 51%]
tests/ethereum/test_general.py::EthTests::test_end_instruction_trace FAILED [ 52%]
tests/ethereum/test_general.py::EthTests::test_event_forwarding_after_state_fork_during_message_call FAILED [ 52%]
tests/ethereum/test_general.py::EthTests::test_function_name_collision FAILED [ 53%]
tests/ethereum/test_general.py::EthTests::test_function_name_with_signature FAILED [ 54%]
tests/ethereum/test_general.py::EthTests::test_gen_testcase_only_if FAILED [ 54%]
tests/ethereum/test_general.py::EthTests::test_graceful_handle_no_alive_states FAILED [ 55%]
tests/ethereum/test_general.py::EthTests::test_invalid_function_signature FAILED [ 55%]
tests/ethereum/test_general.py::EthTests::test_make_symbolic_address FAILED [ 56%]
tests/ethereum/test_general.py::EthTests::test_migrate_integration FAILED [ 57%]
tests/ethereum/test_general.py::EthTests::test_plugins_enable FAILED     [ 57%]
tests/ethereum/test_general.py::EthTests::test_preconstraints FAILED     [ 58%]
tests/ethereum/test_general.py::EthTests::test_reachability SKIPPED      [ 59%]
tests/ethereum/test_general.py::EthTests::test_regression_internal_tx FAILED [ 59%]
tests/ethereum/test_general.py::EthTests::test_selfdestruct_decoupled_account_delete FAILED [ 60%]
tests/ethereum/test_general.py::EthTests::test_solidity_create_contract_no_args FAILED [ 60%]
tests/ethereum/test_general.py::EthTests::test_solidity_create_contract_with_missing_args FAILED [ 61%]
tests/ethereum/test_general.py::EthTests::test_solidity_create_contract_with_not_payable_constructor_and_balance FAILED [ 62%]
tests/ethereum/test_general.py::EthTests::test_solidity_create_contract_with_payable_constructor FAILED [ 62%]
tests/ethereum/test_general.py::EthTests::test_solidity_create_contract_with_payable_constructor_and_balance_owner_insufficient_founds FAILED [ 63%]
tests/ethereum/test_general.py::EthTests::test_states_querying_1325 FAILED [ 63%]
tests/ethereum/test_general.py::EthHelpersTest::test_account_exists FAILED [ 64%]
tests/ethereum/test_general.py::EthHelpersTest::test_concretizer PASSED  [ 65%]
tests/ethereum/test_general.py::EthHelpersTest::test_concretizer_default PASSED [ 65%]
tests/ethereum/test_general.py::EthHelpersTest::test_concretizer_doesnt_overreach PASSED [ 66%]
tests/ethereum/test_general.py::EthSolidityMetadataTests::test_abi_constructor_and_fallback_items FAILED [ 67%]
tests/ethereum/test_general.py::EthSolidityMetadataTests::test_overloaded_functions_and_events FAILED [ 67%]
tests/ethereum/test_general.py::EthSolidityMetadataTests::test_tuple_signature_for_components PASSED [ 68%]
tests/ethereum/test_general.py::EthSpecificTxIntructionTests::test_call_gas FAILED [ 68%]
tests/ethereum/test_general.py::EthSpecificTxIntructionTests::test_delegatecall_env FAILED [ 69%]
tests/ethereum/test_general.py::EthSpecificTxIntructionTests::test_gas_check FAILED [ 70%]
tests/ethereum/test_general.py::EthSpecificTxIntructionTests::test_jmpdest_check FAILED [ 70%]
tests/ethereum/test_general.py::EthSpecificTxIntructionTests::test_selfdestruct FAILED [ 71%]
tests/ethereum/test_general.py::EthSpecificTxIntructionTests::test_selfdestruct_gas FAILED [ 72%]
tests/ethereum/test_general.py::EthPluginTests::test_FilterFunctions_fallback_function_matching FAILED [ 72%]
tests/ethereum/test_general.py::EthPluginTests::test_checkpoint FAILED   [ 73%]
tests/ethereum/test_general.py::EthPluginTests::test_is_main FAILED      [ 73%]
tests/ethereum/test_plugins.py::EthPluginsTests::test_ignore_states FAILED [ 74%]
tests/ethereum/test_plugins.py::EthPluginsTests::test_verbose_trace SKIPPED [ 75%]
tests/ethereum/test_regressions.py::IntegrationTest::test_1102 FAILED    [ 75%]
tests/ethereum/test_regressions.py::IntegrationTest::test_705 PASSED     [ 76%]
tests/ethereum/test_regressions.py::IntegrationTest::test_addmod PASSED  [ 77%]
tests/ethereum/test_regressions.py::IntegrationTest::test_mulmod PASSED  [ 77%]
tests/ethereum/test_regressions.py::IntegrationTest::test_regressions_676 PASSED [ 78%]
tests/ethereum/test_regressions.py::IntegrationTest::test_regressions_678 PASSED [ 78%]
tests/ethereum/test_regressions.py::IntegrationTest::test_regressions_701 PASSED [ 79%]
tests/ethereum/test_regressions.py::IntegrationTest::test_regressions_714 PASSED [ 80%]
tests/ethereum/test_regressions.py::IntegrationTest::test_regressions_735 PASSED [ 80%]
tests/ethereum/test_regressions.py::IntegrationTest::test_regressions_760 PASSED [ 81%]
tests/ethereum/test_regressions.py::IntegrationTest::test_regressions_780 PASSED [ 81%]
tests/ethereum/test_regressions.py::IntegrationTest::test_regressions_795 PASSED [ 82%]
tests/ethereum/test_regressions.py::IntegrationTest::test_regressions_799 PASSED [ 83%]
tests/ethereum/test_regressions.py::IntegrationTest::test_regressions_807 PASSED [ 83%]
tests/ethereum/test_regressions.py::IntegrationTest::test_regressions_808 PASSED [ 84%]
tests/ethereum/test_regressions.py::IntegrationTest::test_regressions_imports PASSED [ 85%]
tests/ethereum/test_regressions.py::IntegrationTest::test_solidity_timeout FAILED [ 85%]
tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_essence1 FAILED [ 86%]
tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_essence2 FAILED [ 86%]
tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_essence3 FAILED [ 87%]
tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_example1 FAILED [ 88%]
tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_example2 FAILED [ 88%]
tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_example3 FAILED [ 89%]
tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_example4 FAILED [ 90%]
tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_example5 FAILED [ 90%]
tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_example6 FAILED [ 91%]
tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_example7 FAILED [ 91%]
tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_example8 FAILED [ 92%]
tests/ethereum/test_sha3.py::EthSha3TestConcrete::test_example_concrete_1 FAILED [ 93%]
tests/ethereum/test_sha3.py::EthSha3TestFake::test_essence1 FAILED       [ 93%]
tests/ethereum/test_sha3.py::EthSha3TestFake::test_essence2 FAILED       [ 94%]
tests/ethereum/test_sha3.py::EthSha3TestFake::test_essence3 FAILED       [ 95%]
tests/ethereum/test_sha3.py::EthSha3TestFake::test_example1 FAILED       [ 95%]
tests/ethereum/test_sha3.py::EthSha3TestFake::test_example2 FAILED       [ 96%]
tests/ethereum/test_sha3.py::EthSha3TestFake::test_example3 FAILED       [ 96%]
tests/ethereum/test_sha3.py::EthSha3TestFake::test_example4 FAILED       [ 97%]
tests/ethereum/test_sha3.py::EthSha3TestFake::test_example5 FAILED       [ 98%]
tests/ethereum/test_sha3.py::EthSha3TestFake::test_example6 FAILED       [ 98%]
tests/ethereum/test_sha3.py::EthSha3TestFake::test_example7 FAILED       [ 99%]
tests/ethereum/test_sha3.py::EthSha3TestFake::test_example8 FAILED       [100%]

=================================== FAILURES ===================================
_________________________ EthRetVal.test_retval_crazy __________________________
tests/ethereum/test_detectors.py:107: in test_retval_crazy
    self._test(name, set())
tests/ethereum/test_detectors.py:78: in _test
    mevm.multi_tx_analysis(
manticore/ethereum/manticore.py:1079: in multi_tx_analysis
    owner_account = self.create_account(balance=10**10, name="owner", address=0x10000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
________________________ EthRetVal.test_retval_lunatic _________________________
tests/ethereum/test_detectors.py:111: in test_retval_lunatic
    self._test(name, set())
tests/ethereum/test_detectors.py:78: in _test
    mevm.multi_tx_analysis(
manticore/ethereum/manticore.py:1079: in multi_tx_analysis
    owner_account = self.create_account(balance=10**10, name="owner", address=0x10000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_________________________ EthRetVal.test_retval_not_ok _________________________
tests/ethereum/test_detectors.py:103: in test_retval_not_ok
    self._test(name, {("Returned value at CALL instruction is not used", False)})
tests/ethereum/test_detectors.py:78: in _test
    mevm.multi_tx_analysis(
manticore/ethereum/manticore.py:1079: in multi_tx_analysis
    owner_account = self.create_account(balance=10**10, name="owner", address=0x10000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
___________________________ EthRetVal.test_retval_ok ___________________________
tests/ethereum/test_detectors.py:99: in test_retval_ok
    self._test(name, set())
tests/ethereum/test_detectors.py:78: in _test
    mevm.multi_tx_analysis(
manticore/ethereum/manticore.py:1079: in multi_tx_analysis
    owner_account = self.create_account(balance=10**10, name="owner", address=0x10000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
____________________ EthSuicidal.test_selfdestruct_true_neg ____________________
tests/ethereum/test_detectors.py:129: in test_selfdestruct_true_neg
    self._test(name, set())
tests/ethereum/test_detectors.py:78: in _test
    mevm.multi_tx_analysis(
manticore/ethereum/manticore.py:1079: in multi_tx_analysis
    owner_account = self.create_account(balance=10**10, name="owner", address=0x10000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
___________________ EthSuicidal.test_selfdestruct_true_neg1 ____________________
tests/ethereum/test_detectors.py:133: in test_selfdestruct_true_neg1
    self._test(name, set())
tests/ethereum/test_detectors.py:78: in _test
    mevm.multi_tx_analysis(
manticore/ethereum/manticore.py:1079: in multi_tx_analysis
    owner_account = self.create_account(balance=10**10, name="owner", address=0x10000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
____________________ EthSuicidal.test_selfdestruct_true_pos ____________________
tests/ethereum/test_detectors.py:119: in test_selfdestruct_true_pos
    self._test(name, {("Reachable SELFDESTRUCT", False)})
tests/ethereum/test_detectors.py:78: in _test
    mevm.multi_tx_analysis(
manticore/ethereum/manticore.py:1079: in multi_tx_analysis
    owner_account = self.create_account(balance=10**10, name="owner", address=0x10000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
________________ EthExternalCallAndLeak.test_etherleak_true_neg ________________
tests/ethereum/test_detectors.py:141: in test_etherleak_true_neg
    self._test(name, set())
tests/ethereum/test_detectors.py:78: in _test
    mevm.multi_tx_analysis(
manticore/ethereum/manticore.py:1079: in multi_tx_analysis
    owner_account = self.create_account(balance=10**10, name="owner", address=0x10000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_______________ EthExternalCallAndLeak.test_etherleak_true_neg1 ________________
tests/ethereum/test_detectors.py:145: in test_etherleak_true_neg1
    self._test(name, set())
tests/ethereum/test_detectors.py:78: in _test
    mevm.multi_tx_analysis(
manticore/ethereum/manticore.py:1079: in multi_tx_analysis
    owner_account = self.create_account(balance=10**10, name="owner", address=0x10000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_______________ EthExternalCallAndLeak.test_etherleak_true_neg2 ________________
tests/ethereum/test_detectors.py:149: in test_etherleak_true_neg2
    self._test(name, {("Reachable external call to sender", False)})
tests/ethereum/test_detectors.py:78: in _test
    mevm.multi_tx_analysis(
manticore/ethereum/manticore.py:1079: in multi_tx_analysis
    owner_account = self.create_account(balance=10**10, name="owner", address=0x10000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_______________ EthExternalCallAndLeak.test_etherleak_true_neg3 ________________
tests/ethereum/test_detectors.py:153: in test_etherleak_true_neg3
    self._test(name, {("Reachable external call to sender", False)})
tests/ethereum/test_detectors.py:78: in _test
    mevm.multi_tx_analysis(
manticore/ethereum/manticore.py:1079: in multi_tx_analysis
    owner_account = self.create_account(balance=10**10, name="owner", address=0x10000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
___________ EthExternalCallAndLeak.test_etherleak_true_pos_msgsender ___________
tests/ethereum/test_detectors.py:191: in test_etherleak_true_pos_msgsender
    self._test(
tests/ethereum/test_detectors.py:78: in _test
    mevm.multi_tx_analysis(
manticore/ethereum/manticore.py:1079: in multi_tx_analysis
    owner_account = self.create_account(balance=10**10, name="owner", address=0x10000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
__________________ EthEnvInstruction.test_predictable_not_ok ___________________
tests/ethereum/test_detectors.py:249: in test_predictable_not_ok
    self._test(
tests/ethereum/test_detectors.py:78: in _test
    mevm.multi_tx_analysis(
manticore/ethereum/manticore.py:1079: in multi_tx_analysis
    owner_account = self.create_account(balance=10**10, name="owner", address=0x10000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_____________________ EthDelegatecall.test_delegatecall_ok _____________________
tests/ethereum/test_detectors.py:272: in test_delegatecall_ok
    self._test(name, set())
tests/ethereum/test_detectors.py:78: in _test
    mevm.multi_tx_analysis(
manticore/ethereum/manticore.py:1079: in multi_tx_analysis
    owner_account = self.create_account(balance=10**10, name="owner", address=0x10000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_____________________ EthRaceCondition.test_race_condition _____________________
tests/ethereum/test_detectors.py:313: in test_race_condition
    self._test(
tests/ethereum/test_detectors.py:78: in _test
    mevm.multi_tx_analysis(
manticore/ethereum/manticore.py:1079: in multi_tx_analysis
    owner_account = self.create_account(balance=10**10, name="owner", address=0x10000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
________________________ EthBalance.test_balance_not_ok ________________________
tests/ethereum/test_detectors.py:416: in test_balance_not_ok
    self._test(name, {(("Manipulable balance used in a strict comparison", False))})
tests/ethereum/test_detectors.py:78: in _test
    mevm.multi_tx_analysis(
manticore/ethereum/manticore.py:1079: in multi_tx_analysis
    owner_account = self.create_account(balance=10**10, name="owner", address=0x10000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
__________________________ EthBalance.test_balance_ok __________________________
tests/ethereum/test_detectors.py:412: in test_balance_ok
    self._test(name, set())
tests/ethereum/test_detectors.py:78: in _test
    mevm.multi_tx_analysis(
manticore/ethereum/manticore.py:1079: in multi_tx_analysis
    owner_account = self.create_account(balance=10**10, name="owner", address=0x10000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
___________________ EthDetectorsIntegrationTest.test_int_ovf ___________________
tests/ethereum/test_general.py:64: in test_int_ovf
    mevm.multi_tx_analysis(filename, tx_limit=1)
manticore/ethereum/manticore.py:1079: in multi_tx_analysis
    owner_account = self.create_account(balance=10**10, name="owner", address=0x10000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
__________________ EthVerifierIntegrationTest.test_propverif ___________________
tests/ethereum/test_general.py:82: in test_propverif
    verifier.manticore_verifier(filename, "TestToken")
manticore/ethereum/verifier.py:152: in manticore_verifier
    m.create_account(balance=10**10, address=address_i, name=f"sender_{n}")
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
________________________ EthAbiTests.test_function_type ________________________
tests/ethereum/test_general.py:352: in test_function_type
    func_id = ABI.function_selector(spec)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/abi.py:212: in function_selector
    s = sha3.keccak_256()
        ^^^^
E   NameError: name 'sha3' is not defined
__________________________ EthAbiTests.test_parse_tx ___________________________
tests/ethereum/test_general.py:133: in test_parse_tx
    user_account = m.create_account(balance=10**10, name="user_account")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
________________ EthAbiTests.test_self_make_and_parse_multi_dyn ________________
tests/ethereum/test_general.py:250: in test_self_make_and_parse_multi_dyn
    d = ABI.function_call("func(bytes,address[])", b"h" * 50, [1, 1, 2, 2, 3, 3])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/abi.py:88: in function_call
    result = ABI.function_selector(type_spec)  # Funcid
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/abi.py:212: in function_selector
    s = sha3.keccak_256()
        ^^^^
E   NameError: name 'sha3' is not defined
_________________________ EthTests.test_account_names __________________________
tests/ethereum/test_general.py:873: in test_account_names
    user_account = m.create_account(name="user_account")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
___________________ EthTests.test_call_with_concretized_args ___________________
tests/ethereum/test_general.py:974: in test_call_with_concretized_args
    owner = m.create_account(balance=20**10)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
___________________ EthTests.test_check_jumpdest_symbolic_pc ___________________
tests/ethereum/test_general.py:740: in test_check_jumpdest_symbolic_pc
    owner=self.mevm.create_account(balance=10000000),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
________ EthTests.test_contract_create_and_access_non_existing_function ________
tests/ethereum/test_general.py:598: in test_contract_create_and_access_non_existing_function
    owner = self.mevm.create_account(balance=10000000)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
__________ EthTests.test_contract_create_and_call_underscore_function __________
tests/ethereum/test_general.py:590: in test_contract_create_and_call_underscore_function
    owner = self.mevm.create_account(balance=300000000)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
____________________ EthTests.test_create_bytecode_contract ____________________
tests/ethereum/test_general.py:664: in test_create_bytecode_contract
    account = self.mevm.create_account(code="0x00AAFF")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_________________ EthTests.test_create_contract_two_instances __________________
tests/ethereum/test_general.py:571: in test_create_contract_two_instances
    owner = self.mevm.create_account(6000000)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
________________ EthTests.test_create_contract_with_string_args ________________
tests/ethereum/test_general.py:562: in test_create_contract_with_string_args
    owner = self.mevm.create_account(balance=200000000)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_______________ EthTests.test_create_contract_with_too_much_args _______________
tests/ethereum/test_general.py:548: in test_create_contract_with_too_much_args
    owner = self.mevm.create_account()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_______________ EthTests.test_emit_did_execute_end_instructions ________________
tests/ethereum/test_general.py:952: in test_emit_did_execute_end_instructions
    mevm.multi_tx_analysis(filename, tx_limit=2, tx_preconstrain=True)
manticore/ethereum/manticore.py:1079: in multi_tx_analysis
    owner_account = self.create_account(balance=10**10, name="owner", address=0x10000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_____________________ EthTests.test_end_instruction_trace ______________________
tests/ethereum/test_general.py:1052: in test_end_instruction_trace
    mevm.multi_tx_analysis(filename, tx_limit=1)
manticore/ethereum/manticore.py:1079: in multi_tx_analysis
    owner_account = self.create_account(balance=10**10, name="owner", address=0x10000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_____ EthTests.test_event_forwarding_after_state_fork_during_message_call ______
tests/ethereum/test_general.py:1141: in test_event_forwarding_after_state_fork_during_message_call
    owner = m.create_account(name="owner", balance=30000000000000000)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
____________________ EthTests.test_function_name_collision _____________________
tests/ethereum/test_general.py:716: in test_function_name_collision
    user_account = self.mevm.create_account(balance=1000000000)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
__________________ EthTests.test_function_name_with_signature __________________
tests/ethereum/test_general.py:816: in test_function_name_with_signature
    user_account = self.mevm.create_account(balance=10**10)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
______________________ EthTests.test_gen_testcase_only_if ______________________
tests/ethereum/test_general.py:758: in test_gen_testcase_only_if
    user_account = self.mevm.create_account(balance=10**10)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
________________ EthTests.test_graceful_handle_no_alive_states _________________
tests/ethereum/test_general.py:1172: in test_graceful_handle_no_alive_states
    user_account = m.create_account(balance=10**10)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
___________________ EthTests.test_invalid_function_signature ___________________
tests/ethereum/test_general.py:616: in test_invalid_function_signature
    user_account = self.mevm.create_account(balance=10**10)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_____________________ EthTests.test_make_symbolic_address ______________________
tests/ethereum/test_general.py:998: in test_make_symbolic_address
    owner = self.mevm.create_account(balance=1)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
______________________ EthTests.test_migrate_integration _______________________
tests/ethereum/test_general.py:841: in test_migrate_integration
    owner_account = m.create_account(balance=10**10)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_________________________ EthTests.test_plugins_enable _________________________
tests/ethereum/test_general.py:1369: in test_plugins_enable
    creator_account = m.create_account(balance=10000000000)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_________________________ EthTests.test_preconstraints _________________________
tests/ethereum/test_general.py:1334: in test_preconstraints
    creator_account = m.create_account(balance=10**10)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_____________________ EthTests.test_regression_internal_tx _____________________
tests/ethereum/test_general.py:889: in test_regression_internal_tx
    owner_account = m.create_account(balance=10**10)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_____________ EthTests.test_selfdestruct_decoupled_account_delete ______________
tests/ethereum/test_general.py:645: in test_selfdestruct_decoupled_account_delete
    user_account = self.mevm.create_account(balance=1000000000000000000000)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
________________ EthTests.test_solidity_create_contract_no_args ________________
tests/ethereum/test_general.py:490: in test_solidity_create_contract_no_args
    owner = self.mevm.create_account(balance=10**10)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
___________ EthTests.test_solidity_create_contract_with_missing_args ___________
tests/ethereum/test_general.py:536: in test_solidity_create_contract_with_missing_args
    owner = self.mevm.create_account()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_ EthTests.test_solidity_create_contract_with_not_payable_constructor_and_balance _
tests/ethereum/test_general.py:500: in test_solidity_create_contract_with_not_payable_constructor_and_balance
    owner = self.mevm.create_account()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_______ EthTests.test_solidity_create_contract_with_payable_constructor ________
tests/ethereum/test_general.py:528: in test_solidity_create_contract_with_payable_constructor
    owner = self.mevm.create_account(balance=10**10)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_ EthTests.test_solidity_create_contract_with_payable_constructor_and_balance_owner_insufficient_founds _
tests/ethereum/test_general.py:515: in test_solidity_create_contract_with_payable_constructor_and_balance_owner_insufficient_founds
    owner = self.mevm.create_account(balance=1)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
______________________ EthTests.test_states_querying_1325 ______________________
tests/ethereum/test_general.py:677: in test_states_querying_1325
    owner = self.mevm.create_account(balance=10**10)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
______________________ EthHelpersTest.test_account_exists ______________________
tests/ethereum/test_general.py:1448: in test_account_exists
    empty = world.create_account(nonce=0, balance=0, code=b"")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_______ EthSolidityMetadataTests.test_abi_constructor_and_fallback_items _______
tests/ethereum/test_general.py:1499: in test_abi_constructor_and_fallback_items
    user_account = m.create_account(balance=100000000000, name="user_account")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
________ EthSolidityMetadataTests.test_overloaded_functions_and_events _________
tests/ethereum/test_general.py:1558: in test_overloaded_functions_and_events
    user_account = m.create_account(balance=100000000, name="user_account")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
__________________ EthSpecificTxIntructionTests.test_call_gas __________________
tests/ethereum/test_general.py:1809: in test_call_gas
    m.create_account(address=0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF)
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
______________ EthSpecificTxIntructionTests.test_delegatecall_env ______________
tests/ethereum/test_general.py:1696: in test_delegatecall_env
    world.create_account(
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_________________ EthSpecificTxIntructionTests.test_gas_check __________________
tests/ethereum/test_general.py:1763: in test_gas_check
    world.create_account(
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_______________ EthSpecificTxIntructionTests.test_jmpdest_check ________________
tests/ethereum/test_general.py:1640: in test_jmpdest_check
    world.create_account(
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
________________ EthSpecificTxIntructionTests.test_selfdestruct ________________
tests/ethereum/test_general.py:1786: in test_selfdestruct
    m.create_account(
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
______________ EthSpecificTxIntructionTests.test_selfdestruct_gas ______________
tests/ethereum/test_general.py:1901: in test_selfdestruct_gas
    empty = m.create_account(address=0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
________ EthPluginTests.test_FilterFunctions_fallback_function_matching ________
tests/ethereum/test_general.py:1968: in test_FilterFunctions_fallback_function_matching
    creator_account = m.create_account(balance=10000000000000)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
________________________ EthPluginTests.test_checkpoint ________________________
tests/ethereum/test_general.py:2005: in test_checkpoint
    creator_account = m.create_account(balance=10000000000)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:863: in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
manticore/platforms/evm.py:3187: in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
E   TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_________________________ EthPluginTests.test_is_main __________________________
tests/ethereum/test_general.py:2062: in test_is_main
    m: ManticoreEVM = ManticoreEVM()
                      ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
______________________ EthPluginsTests.test_ignore_states ______________________
tests/ethereum/test_plugins.py:16: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
__________________________ IntegrationTest.test_1102 ___________________________
tests/ethereum/test_regressions.py:238: in test_1102
    self._simple_cli_run(
tests/ethereum/test_regressions.py:68: in _simple_cli_run
    subprocess.check_call(command, stdout=subprocess.PIPE, cwd=working_dir)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py:413: in check_call
    raise CalledProcessError(retcode, cmd)
E   subprocess.CalledProcessError: Command '['/opt/homebrew/opt/python@3.11/bin/python3.11', '-m', 'manticore', '--thorough-mode', '--workspace', '/var/folders/1p/83ym86td7w701tdl_wl1rctm0000gn/T/tmpz9m9w7c_', '--txlimit', '1', '1102.sol']' returned non-zero exit status 1.
----------------------------- Captured stderr call -----------------------------
WARNING:manticore.core.manticore:Manticore is only supported on Linux. Proceed at your own risk!
/Users/user/Documents/GitHub/manticore/manticore/__main__.py:8: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/user/Documents/GitHub/manticore/manticore/__main__.py", line 267, in <module>
    main()
  File "/Users/user/Documents/GitHub/manticore/manticore/__main__.py", line 43, in main
    ethereum_main(args, logger)
  File "/Users/user/Documents/GitHub/manticore/manticore/ethereum/cli.py", line 145, in ethereum_main
    m.finalize(only_alive_states=args.only_alive_testcases)
  File "/Users/user/Documents/GitHub/manticore/manticore/core/manticore.py", line 177, in newFunction
    return func(self, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/GitHub/manticore/manticore/ethereum/manticore.py", line 1779, in finalize
    proc.start()
  File "/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'ManticoreEVM.finalize.<locals>.worker_finalize'
____________________ IntegrationTest.test_solidity_timeout _____________________
tests/ethereum/test_regressions.py:91: in test_solidity_timeout
    output = subprocess.check_output(cmd)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py:466: in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py:571: in run
    raise CalledProcessError(retcode, process.args,
E   subprocess.CalledProcessError: Command '['/opt/homebrew/opt/python@3.11/bin/python3.11', '-m', 'manticore', '--workspace', '/var/folders/1p/83ym86td7w701tdl_wl1rctm0000gn/T/tmpm5oqref2/workspace', '--core.timeout', '4', '--no-color', 'tests/ethereum/contracts/int_overflow.sol']' returned non-zero exit status 1.
----------------------------- Captured stderr call -----------------------------
WARNING:manticore.core.manticore:Manticore is only supported on Linux. Proceed at your own risk!
/Users/user/Documents/GitHub/manticore/manticore/__main__.py:8: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/user/Documents/GitHub/manticore/manticore/__main__.py", line 267, in <module>
    main()
  File "/Users/user/Documents/GitHub/manticore/manticore/__main__.py", line 43, in main
    ethereum_main(args, logger)
  File "/Users/user/Documents/GitHub/manticore/manticore/ethereum/cli.py", line 133, in ethereum_main
    m.multi_tx_analysis(
  File "/Users/user/Documents/GitHub/manticore/manticore/ethereum/manticore.py", line 1079, in multi_tx_analysis
    owner_account = self.create_account(balance=10**10, name="owner", address=0x10000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/GitHub/manticore/manticore/ethereum/manticore.py", line 863, in create_account
    world.create_account(address, balance, code=code, storage=None, nonce=nonce)
  File "/Users/user/Documents/GitHub/manticore/manticore/platforms/evm.py", line 3187, in create_account
    value = sha3.keccak_256(data).hexdigest()
            ^^^^^^^^^^^^^^^^^^^^^
TypeError: keccak_256() takes from 0 to 1 positional arguments but 2 were given
_____________________ EthSha3TestSymbolicate.test_essence1 _____________________
tests/ethereum/test_sha3.py:27: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
_____________________ EthSha3TestSymbolicate.test_essence2 _____________________
tests/ethereum/test_sha3.py:27: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
_____________________ EthSha3TestSymbolicate.test_essence3 _____________________
tests/ethereum/test_sha3.py:27: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
_____________________ EthSha3TestSymbolicate.test_example1 _____________________
tests/ethereum/test_sha3.py:27: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
_____________________ EthSha3TestSymbolicate.test_example2 _____________________
tests/ethereum/test_sha3.py:27: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
_____________________ EthSha3TestSymbolicate.test_example3 _____________________
tests/ethereum/test_sha3.py:27: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
_____________________ EthSha3TestSymbolicate.test_example4 _____________________
tests/ethereum/test_sha3.py:27: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
_____________________ EthSha3TestSymbolicate.test_example5 _____________________
tests/ethereum/test_sha3.py:27: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
_____________________ EthSha3TestSymbolicate.test_example6 _____________________
tests/ethereum/test_sha3.py:27: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
_____________________ EthSha3TestSymbolicate.test_example7 _____________________
tests/ethereum/test_sha3.py:27: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
_____________________ EthSha3TestSymbolicate.test_example8 _____________________
tests/ethereum/test_sha3.py:27: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
_________________ EthSha3TestConcrete.test_example_concrete_1 __________________
tests/ethereum/test_sha3.py:428: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
________________________ EthSha3TestFake.test_essence1 _________________________
tests/ethereum/test_sha3.py:477: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
________________________ EthSha3TestFake.test_essence2 _________________________
tests/ethereum/test_sha3.py:477: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
________________________ EthSha3TestFake.test_essence3 _________________________
tests/ethereum/test_sha3.py:477: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
________________________ EthSha3TestFake.test_example1 _________________________
tests/ethereum/test_sha3.py:477: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
________________________ EthSha3TestFake.test_example2 _________________________
tests/ethereum/test_sha3.py:477: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
________________________ EthSha3TestFake.test_example3 _________________________
tests/ethereum/test_sha3.py:477: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
________________________ EthSha3TestFake.test_example4 _________________________
tests/ethereum/test_sha3.py:477: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
________________________ EthSha3TestFake.test_example5 _________________________
tests/ethereum/test_sha3.py:477: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
________________________ EthSha3TestFake.test_example6 _________________________
tests/ethereum/test_sha3.py:477: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
________________________ EthSha3TestFake.test_example7 _________________________
tests/ethereum/test_sha3.py:477: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
________________________ EthSha3TestFake.test_example8 _________________________
tests/ethereum/test_sha3.py:477: in setUp
    self.mevm = ManticoreEVM()
                ^^^^^^^^^^^^^^
manticore/ethereum/manticore.py:416: in __init__
    super().__init__(initial_state, **kwargs)
manticore/core/manticore.py:330: in __init__
    {
manticore/core/manticore.py:126: in _manticore_multiprocessing
    self._manager.start(raise_signal)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py:563: in start
    self._process.start()
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py:60: in dump
    ForkingPickler(file, protocol).dump(obj)
E   AttributeError: Can't pickle local object 'ManticoreBase._manticore_multiprocessing.<locals>.raise_signal'
=============================== warnings summary ===============================
tests/ethereum/test_general.py:4
  /Users/user/Documents/GitHub/manticore/tests/ethereum/test_general.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================= slowest 10 durations =============================
2.46s call     tests/ethereum/test_general.py::EthAbiTests::test_serialize_bytesM_symbolic
0.69s call     tests/ethereum/test_general.py::EthAbiTests::test_serialize_bytes_symbolic
0.69s call     tests/ethereum/test_general.py::EthAbiTests::test_simple_types_ints_symbolic
0.41s call     tests/ethereum/test_general.py::EthAbiTests::test_simple_types_ints_symbolic1
0.37s call     tests/ethereum/test_regressions.py::IntegrationTest::test_regressions_807
0.35s call     tests/ethereum/test_regressions.py::IntegrationTest::test_regressions_808
0.34s call     tests/ethereum/test_regressions.py::IntegrationTest::test_1102
0.34s call     tests/ethereum/test_regressions.py::IntegrationTest::test_regressions_799
0.33s call     tests/ethereum/test_regressions.py::IntegrationTest::test_solidity_timeout
0.33s call     tests/ethereum/test_regressions.py::IntegrationTest::test_mulmod
=========================== short test summary info ============================
FAILED tests/ethereum/test_detectors.py::EthRetVal::test_retval_crazy - TypeE...
FAILED tests/ethereum/test_detectors.py::EthRetVal::test_retval_lunatic - Typ...
FAILED tests/ethereum/test_detectors.py::EthRetVal::test_retval_not_ok - Type...
FAILED tests/ethereum/test_detectors.py::EthRetVal::test_retval_ok - TypeErro...
FAILED tests/ethereum/test_detectors.py::EthSuicidal::test_selfdestruct_true_neg
FAILED tests/ethereum/test_detectors.py::EthSuicidal::test_selfdestruct_true_neg1
FAILED tests/ethereum/test_detectors.py::EthSuicidal::test_selfdestruct_true_pos
FAILED tests/ethereum/test_detectors.py::EthExternalCallAndLeak::test_etherleak_true_neg
FAILED tests/ethereum/test_detectors.py::EthExternalCallAndLeak::test_etherleak_true_neg1
FAILED tests/ethereum/test_detectors.py::EthExternalCallAndLeak::test_etherleak_true_neg2
FAILED tests/ethereum/test_detectors.py::EthExternalCallAndLeak::test_etherleak_true_neg3
FAILED tests/ethereum/test_detectors.py::EthExternalCallAndLeak::test_etherleak_true_pos_msgsender
FAILED tests/ethereum/test_detectors.py::EthEnvInstruction::test_predictable_not_ok
FAILED tests/ethereum/test_detectors.py::EthDelegatecall::test_delegatecall_ok
FAILED tests/ethereum/test_detectors.py::EthRaceCondition::test_race_condition
FAILED tests/ethereum/test_detectors.py::EthBalance::test_balance_not_ok - Ty...
FAILED tests/ethereum/test_detectors.py::EthBalance::test_balance_ok - TypeEr...
FAILED tests/ethereum/test_general.py::EthDetectorsIntegrationTest::test_int_ovf
FAILED tests/ethereum/test_general.py::EthVerifierIntegrationTest::test_propverif
FAILED tests/ethereum/test_general.py::EthAbiTests::test_function_type - Name...
FAILED tests/ethereum/test_general.py::EthAbiTests::test_parse_tx - TypeError...
FAILED tests/ethereum/test_general.py::EthAbiTests::test_self_make_and_parse_multi_dyn
FAILED tests/ethereum/test_general.py::EthTests::test_account_names - TypeErr...
FAILED tests/ethereum/test_general.py::EthTests::test_call_with_concretized_args
FAILED tests/ethereum/test_general.py::EthTests::test_check_jumpdest_symbolic_pc
FAILED tests/ethereum/test_general.py::EthTests::test_contract_create_and_access_non_existing_function
FAILED tests/ethereum/test_general.py::EthTests::test_contract_create_and_call_underscore_function
FAILED tests/ethereum/test_general.py::EthTests::test_create_bytecode_contract
FAILED tests/ethereum/test_general.py::EthTests::test_create_contract_two_instances
FAILED tests/ethereum/test_general.py::EthTests::test_create_contract_with_string_args
FAILED tests/ethereum/test_general.py::EthTests::test_create_contract_with_too_much_args
FAILED tests/ethereum/test_general.py::EthTests::test_emit_did_execute_end_instructions
FAILED tests/ethereum/test_general.py::EthTests::test_end_instruction_trace
FAILED tests/ethereum/test_general.py::EthTests::test_event_forwarding_after_state_fork_during_message_call
FAILED tests/ethereum/test_general.py::EthTests::test_function_name_collision
FAILED tests/ethereum/test_general.py::EthTests::test_function_name_with_signature
FAILED tests/ethereum/test_general.py::EthTests::test_gen_testcase_only_if - ...
FAILED tests/ethereum/test_general.py::EthTests::test_graceful_handle_no_alive_states
FAILED tests/ethereum/test_general.py::EthTests::test_invalid_function_signature
FAILED tests/ethereum/test_general.py::EthTests::test_make_symbolic_address
FAILED tests/ethereum/test_general.py::EthTests::test_migrate_integration - T...
FAILED tests/ethereum/test_general.py::EthTests::test_plugins_enable - TypeEr...
FAILED tests/ethereum/test_general.py::EthTests::test_preconstraints - TypeEr...
FAILED tests/ethereum/test_general.py::EthTests::test_regression_internal_tx
FAILED tests/ethereum/test_general.py::EthTests::test_selfdestruct_decoupled_account_delete
FAILED tests/ethereum/test_general.py::EthTests::test_solidity_create_contract_no_args
FAILED tests/ethereum/test_general.py::EthTests::test_solidity_create_contract_with_missing_args
FAILED tests/ethereum/test_general.py::EthTests::test_solidity_create_contract_with_not_payable_constructor_and_balance
FAILED tests/ethereum/test_general.py::EthTests::test_solidity_create_contract_with_payable_constructor
FAILED tests/ethereum/test_general.py::EthTests::test_solidity_create_contract_with_payable_constructor_and_balance_owner_insufficient_founds
FAILED tests/ethereum/test_general.py::EthTests::test_states_querying_1325 - ...
FAILED tests/ethereum/test_general.py::EthHelpersTest::test_account_exists - ...
FAILED tests/ethereum/test_general.py::EthSolidityMetadataTests::test_abi_constructor_and_fallback_items
FAILED tests/ethereum/test_general.py::EthSolidityMetadataTests::test_overloaded_functions_and_events
FAILED tests/ethereum/test_general.py::EthSpecificTxIntructionTests::test_call_gas
FAILED tests/ethereum/test_general.py::EthSpecificTxIntructionTests::test_delegatecall_env
FAILED tests/ethereum/test_general.py::EthSpecificTxIntructionTests::test_gas_check
FAILED tests/ethereum/test_general.py::EthSpecificTxIntructionTests::test_jmpdest_check
FAILED tests/ethereum/test_general.py::EthSpecificTxIntructionTests::test_selfdestruct
FAILED tests/ethereum/test_general.py::EthSpecificTxIntructionTests::test_selfdestruct_gas
FAILED tests/ethereum/test_general.py::EthPluginTests::test_FilterFunctions_fallback_function_matching
FAILED tests/ethereum/test_general.py::EthPluginTests::test_checkpoint - Type...
FAILED tests/ethereum/test_general.py::EthPluginTests::test_is_main - Attribu...
FAILED tests/ethereum/test_plugins.py::EthPluginsTests::test_ignore_states - ...
FAILED tests/ethereum/test_regressions.py::IntegrationTest::test_1102 - subpr...
FAILED tests/ethereum/test_regressions.py::IntegrationTest::test_solidity_timeout
FAILED tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_essence1 - A...
FAILED tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_essence2 - A...
FAILED tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_essence3 - A...
FAILED tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_example1 - A...
FAILED tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_example2 - A...
FAILED tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_example3 - A...
FAILED tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_example4 - A...
FAILED tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_example5 - A...
FAILED tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_example6 - A...
FAILED tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_example7 - A...
FAILED tests/ethereum/test_sha3.py::EthSha3TestSymbolicate::test_example8 - A...
FAILED tests/ethereum/test_sha3.py::EthSha3TestConcrete::test_example_concrete_1
FAILED tests/ethereum/test_sha3.py::EthSha3TestFake::test_essence1 - Attribut...
FAILED tests/ethereum/test_sha3.py::EthSha3TestFake::test_essence2 - Attribut...
FAILED tests/ethereum/test_sha3.py::EthSha3TestFake::test_essence3 - Attribut...
FAILED tests/ethereum/test_sha3.py::EthSha3TestFake::test_example1 - Attribut...
FAILED tests/ethereum/test_sha3.py::EthSha3TestFake::test_example2 - Attribut...
FAILED tests/ethereum/test_sha3.py::EthSha3TestFake::test_example3 - Attribut...
FAILED tests/ethereum/test_sha3.py::EthSha3TestFake::test_example4 - Attribut...
FAILED tests/ethereum/test_sha3.py::EthSha3TestFake::test_example5 - Attribut...
FAILED tests/ethereum/test_sha3.py::EthSha3TestFake::test_example6 - Attribut...
FAILED tests/ethereum/test_sha3.py::EthSha3TestFake::test_example7 - Attribut...
FAILED tests/ethereum/test_sha3.py::EthSha3TestFake::test_example8 - Attribut...
============ 89 failed, 59 passed, 13 skipped, 1 warning in 16.13s =============
